// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package fib_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FibonnaciClient is the client API for Fibonnaci service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FibonnaciClient interface {
	GetFibonacciSlice(ctx context.Context, in *FibRequest, opts ...grpc.CallOption) (*FibResponse, error)
}

type fibonnaciClient struct {
	cc grpc.ClientConnInterface
}

func NewFibonnaciClient(cc grpc.ClientConnInterface) FibonnaciClient {
	return &fibonnaciClient{cc}
}

func (c *fibonnaciClient) GetFibonacciSlice(ctx context.Context, in *FibRequest, opts ...grpc.CallOption) (*FibResponse, error) {
	out := new(FibResponse)
	err := c.cc.Invoke(ctx, "/fib_proto.Fibonnaci/GetFibonacciSlice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FibonnaciServer is the server API for Fibonnaci service.
// All implementations must embed UnimplementedFibonnaciServer
// for forward compatibility
type FibonnaciServer interface {
	GetFibonacciSlice(context.Context, *FibRequest) (*FibResponse, error)
	mustEmbedUnimplementedFibonnaciServer()
}

// UnimplementedFibonnaciServer must be embedded to have forward compatible implementations.
type UnimplementedFibonnaciServer struct {
}

func (UnimplementedFibonnaciServer) GetFibonacciSlice(context.Context, *FibRequest) (*FibResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFibonacciSlice not implemented")
}
func (UnimplementedFibonnaciServer) mustEmbedUnimplementedFibonnaciServer() {}

// UnsafeFibonnaciServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FibonnaciServer will
// result in compilation errors.
type UnsafeFibonnaciServer interface {
	mustEmbedUnimplementedFibonnaciServer()
}

func RegisterFibonnaciServer(s grpc.ServiceRegistrar, srv FibonnaciServer) {
	s.RegisterService(&Fibonnaci_ServiceDesc, srv)
}

func _Fibonnaci_GetFibonacciSlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FibRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibonnaciServer).GetFibonacciSlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fib_proto.Fibonnaci/GetFibonacciSlice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibonnaciServer).GetFibonacciSlice(ctx, req.(*FibRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Fibonnaci_ServiceDesc is the grpc.ServiceDesc for Fibonnaci service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fibonnaci_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fib_proto.Fibonnaci",
	HandlerType: (*FibonnaciServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFibonacciSlice",
			Handler:    _Fibonnaci_GetFibonacciSlice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fib.proto",
}
